"""Renders a change plan as Ansible and Terraform, for review and pipeline use.

These are generated, not executed. Terraform in particular owns its resources
through state, and CSAP has no state for objects it created over REST, so an
apply would try to recreate them. Generating the code lets a team review it,
commit it and run it under their own pipeline and state backend.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from typing import Any

from app.plugins.base import ChangePlan

CONFIG_ROOT = "/api/fmc_config/v1/domain"

# CiscoDevNet/fmc resource type per workbook sheet.
TERRAFORM_RESOURCES = {
    "Hosts": "fmc_host_objects",
    "Networks": "fmc_network_objects",
    "Ranges": "fmc_range_objects",
    "Ports": "fmc_port_objects",
    "NetworkGroups": "fmc_network_group_objects",
    "AccessRules": "fmc_access_rules",
}


def _identifier(name: str, fallback: str = "object") -> str:
    """A safe HCL/Ansible identifier derived from an FMC object name."""
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name).strip("_").lower()
    if not cleaned or cleaned[0].isdigit():
        cleaned = f"{fallback}_{cleaned}" if cleaned else fallback
    return cleaned


def _header(kind: str, change_name: str, host: str, total: int) -> str:
    stamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        f"Generated by Cisco Security Automation Platform on {stamp}\n"
        f"Source workbook: {change_name}\n"
        f"Target FMC:      {host}\n"
        f"Operations:      {total}\n"
        f"\n"
        f"Review before running. This {kind} was generated from a change plan that\n"
        f"was validated against a specific snapshot of the FMC; if the device has\n"
        f"changed since, regenerate it."
    )


# --------------------------------------------------------------------------
# Ansible
# --------------------------------------------------------------------------
def render_ansible(plan: ChangePlan, change_name: str, host: str) -> dict[str, str]:
    operations = plan.creates + plan.updates + plan.deletes
    lines: list[str] = ["---"]
    lines += [f"# {line}" for line in _header("playbook", change_name, host, len(operations)).split("\n")]
    lines += [
        "#",
        "# Uses ansible.builtin.uri, so no external collection is required.",
        "# Run with:",
        "#   export FMC_USERNAME=apiuser FMC_PASSWORD=...",
        "#   ansible-playbook fmc_change.yml",
        "",
        "- name: Apply CSAP change to Cisco Secure Firewall",
        "  hosts: localhost",
        "  gather_facts: false",
        "  vars:",
        f'    fmc_host: "{host}"',
        '    fmc_username: "{{ lookup(\'env\', \'FMC_USERNAME\') }}"',
        '    fmc_password: "{{ lookup(\'env\', \'FMC_PASSWORD\') }}"',
        "    # Lab FMCs use a self-signed certificate. Set true once a real cert is installed.",
        "    validate_certs: false",
        "",
        "  tasks:",
        "    - name: Obtain an FMC session token",
        "      ansible.builtin.uri:",
        '        url: "https://{{ fmc_host }}/api/fmc_platform/v1/auth/generatetoken"',
        "        method: POST",
        '        user: "{{ fmc_username }}"',
        '        password: "{{ fmc_password }}"',
        "        force_basic_auth: true",
        '        validate_certs: "{{ validate_certs }}"',
        "        status_code: [200, 204]",
        "      register: fmc_auth",
        "      no_log: true",
        "",
        "    - name: Keep the token and domain for the tasks below",
        "      ansible.builtin.set_fact:",
        '        fmc_token: "{{ fmc_auth.x_auth_access_token }}"',
        '        fmc_domain: "{{ fmc_auth.domain_uuid }}"',
        "      no_log: true",
    ]

    if not operations:
        lines += ["", "    # This plan contained no operations."]
        return {"fmc_change.yml": "\n".join(lines) + "\n"}

    for index, entry in enumerate(operations, start=1):
        method, path = _endpoint(entry)
        label = f"{index}. {entry['action']} {entry.get('entity', 'object')} {entry['name']}"
        lines += [
            "",
            f"    - name: {label}",
            "      ansible.builtin.uri:",
            f'        url: "https://{{{{ fmc_host }}}}{CONFIG_ROOT}/{{{{ fmc_domain }}}}/{path}"',
            f"        method: {method}",
            "        headers:",
            '          X-auth-access-token: "{{ fmc_token }}"',
            '        validate_certs: "{{ validate_certs }}"',
        ]
        body = _body(entry)
        if body is not None:
            lines += ["        body_format: json", f"        body: {json.dumps(body)}"]
            lines += ["        status_code: [200, 201, 202]"]
        else:
            lines += ["        status_code: [200, 202, 204]"]

    return {"fmc_change.yml": "\n".join(lines) + "\n"}


# --------------------------------------------------------------------------
# Terraform
# --------------------------------------------------------------------------
def render_terraform(plan: ChangePlan, change_name: str, host: str) -> dict[str, str]:
    total = plan.total
    files: dict[str, str] = {}

    files["providers.tf"] = (
        "\n".join(f"# {line}" for line in _header("configuration", change_name, host, total).split("\n"))
        + """

terraform {
  required_version = ">= 1.5"
  required_providers {
    fmc = {
      source  = "CiscoDevNet/fmc"
      version = "~> 1.4"
    }
  }
}

provider "fmc" {
  fmc_host                 = var.fmc_host
  fmc_username             = var.fmc_username
  fmc_password             = var.fmc_password
  fmc_insecure_skip_verify = var.fmc_insecure_skip_verify
}
"""
    )

    files["variables.tf"] = f'''variable "fmc_host" {{
  description = "FMC management address"
  type        = string
  default     = "{host}"
}}

variable "fmc_username" {{
  description = "FMC API account. Export TF_VAR_fmc_username."
  type        = string
  sensitive   = true
}}

variable "fmc_password" {{
  description = "FMC API password. Export TF_VAR_fmc_password."
  type        = string
  sensitive   = true
}}

variable "fmc_insecure_skip_verify" {{
  description = "Set false once the FMC presents a CA-signed certificate."
  type        = bool
  default     = true
}}
'''

    body: list[str] = []
    used: set[str] = set()

    for entry in plan.creates + plan.updates:
        block = _terraform_resource(entry, used)
        if block:
            body.append(block)

    if plan.deletes:
        body.append(
            "# Terraform removes an object by deleting its resource block, so the\n"
            "# deletions below cannot be expressed here. Remove the matching resource\n"
            "# from your configuration, or delete them through CSAP's REST engine.\n"
            + "\n".join(f"#   delete {e.get('entity', 'object')} {e['name']}" for e in plan.deletes)
        )

    if not body:
        body.append("# This plan produced no resources Terraform can manage.")

    files["main.tf"] = "\n\n".join(body) + "\n"

    files["README.md"] = f"""# Terraform for `{change_name}`

Generated by CSAP against `{host}`.

```bash
export TF_VAR_fmc_username='apiuser'
export TF_VAR_fmc_password='...'

terraform init
terraform plan
terraform apply
```

## Before you run this

Terraform manages resources through **state**. These objects may already exist on
the FMC - CSAP validated this plan against a live snapshot. Applying without
importing them first will try to create duplicates and fail.

Import anything that already exists:

```bash
terraform import fmc_network_objects.example <object-uuid>
```

Treat this output as a starting point for managing the firewall in Terraform,
not as a drop-in replacement for the REST engine.
"""

    return files


def _terraform_resource(entry: dict[str, Any], used: set[str]) -> str | None:
    resource = TERRAFORM_RESOURCES.get(entry.get("sheet", ""))
    payload = entry.get("payload") or {}
    if not resource:
        return None

    name = _identifier(entry["name"])
    while name in used:
        name = f"{name}_x"
    used.add(name)

    lines = [f'resource "{resource}" "{name}" {{', f'  name = "{_escape(entry["name"])}"']

    if entry["sheet"] in {"Hosts", "Networks", "Ranges"}:
        lines.append(f'  value = "{_escape(payload.get("value", ""))}"')
    elif entry["sheet"] == "Ports":
        lines.append(f'  port     = "{_escape(payload.get("port", ""))}"')
        lines.append(f'  protocol = "{_escape(payload.get("protocol", ""))}"')
    elif entry["sheet"] == "NetworkGroups":
        for member in payload.get("objects") or []:
            lines += [
                "  objects {",
                f'    id   = "{_escape(member.get("id", ""))}"',
                f'    type = "{_escape(member.get("type", ""))}"',
                "  }",
            ]
        for literal in payload.get("literals") or []:
            lines += [
                "  literals {",
                f'    value = "{_escape(literal.get("value", ""))}"',
                f'    type  = "{_escape(literal.get("type", "Network"))}"',
                "  }",
            ]
    elif entry["sheet"] == "AccessRules":
        lines.append(f'  acp    = "{_escape(entry.get("policy_id", ""))}"')
        lines.append(f'  action = "{_escape(str(payload.get("action", "ALLOW")).lower())}"')
        lines.append(f"  enabled = {str(payload.get('enabled', True)).lower()}")
        if payload.get("logBegin") or payload.get("logEnd"):
            lines.append(f"  log_begin = {str(payload.get('logBegin', False)).lower()}")
            lines.append(f"  log_end   = {str(payload.get('logEnd', False)).lower()}")
            lines.append("  send_events_to_fmc = true")

    if payload.get("description"):
        lines.append(f'  description = "{_escape(payload["description"])}"')

    lines.append("}")
    return "\n".join(lines)


def _escape(value: Any) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


# --------------------------------------------------------------------------
def _endpoint(entry: dict[str, Any]) -> tuple[str, str]:
    if entry.get("target") == "access_rule":
        base = f"policy/accesspolicies/{entry.get('policy_id', '')}/accessrules"
    else:
        base = f"object/{entry['kind']}"
    if entry["action"] == "create":
        return "POST", base
    return ("PUT" if entry["action"] == "update" else "DELETE", f"{base}/{entry.get('id', '')}")


def _body(entry: dict[str, Any]) -> dict[str, Any] | None:
    if entry["action"] == "create":
        return entry.get("payload")
    if entry["action"] == "update":
        return {**(entry.get("payload") or {}), "id": entry.get("id", "")}
    return None
